### ISSUE TITLE
同学，你获得老师的许可了么？就直接公开老师的课件。

### ISSUE THREAD

**Issue by cchd0001** [HuangCongQing/UCAS_Course_2019#1]

**Comment by HuangCongQing** [comment]
没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(*^▽^*)

**Comment by fenice8023** [comment]
那您看可以了不？我全删了。如果还不可以的话，您告诉我还要做什么，我一定纠正。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuangCongQing/UCAS_Course_2019"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 晚上6:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [HuangCongQing/UCAS_Course_2019] 同学，你获得老师的许可了么？就直接公开老师的课件。 (#1)





 
没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(^▽^)
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cchd0001** [comment]
> 没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(^▽^)

你是哪位？

**Comment by cchd0001** [comment]
> 那您看可以了不？我全删了。如果还不可以的话，您告诉我还要做什么，我一定纠正。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HuangCongQing/UCAS_Course_2019" ***@***.***&gt;; 发送时间:&nbsp;2021年8月24日(星期二) 晚上6:51 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [HuangCongQing/UCAS_Course_2019] 同学，你获得老师的许可了么？就直接公开老师的课件。 (#1) 没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(^▽^) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

您是哪位？

**Comment by cchd0001** [comment]
> 没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(_^▽^_)

了解

**Comment by fenice8023** [comment]
不是你说我公开了你老师的课件吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuangCongQing/UCAS_Course_2019"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月25日(星期三) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuangCongQing/UCAS_Course_2019] 同学，你获得老师的许可了么？就直接公开老师的课件。 (#1)





  
没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(^▽^)
  
你是哪位？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fenice8023** [comment]
嗯嗯，以后常联系





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuangCongQing/UCAS_Course_2019"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月25日(星期三) 中午1:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuangCongQing/UCAS_Course_2019] 同学，你获得老师的许可了么？就直接公开老师的课件。 (#1)





  
没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(^▽^)
  
了解
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cchd0001** [comment]
> 嗯嗯，以后常联系
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HuangCongQing/UCAS_Course_2019" ***@***.***&gt;; 发送时间:&nbsp;2021年8月25日(星期三) 中午1:09 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [HuangCongQing/UCAS_Course_2019] 同学，你获得老师的许可了么？就直接公开老师的课件。 (#1) 没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(^▽^) 了解 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

哦哦，俩账号是一个人啊。

**Comment by fenice8023** [comment]
嗯嗯，改了个名字。嘿嘿




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuangCongQing/UCAS_Course_2019"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月25日(星期三) 中午1:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuangCongQing/UCAS_Course_2019] 同学，你获得老师的许可了么？就直接公开老师的课件。 (#1)





  
嗯嗯，以后常联系
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HuangCongQing/UCAS_Course_2019" @.&gt;; 发送时间:&nbsp;2021年8月25日(星期三) 中午1:09 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [HuangCongQing/UCAS_Course_2019] 同学，你获得老师的许可了么？就直接公开老师的课件。 (#1) 没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(^▽^) 了解 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
哦哦，俩账号是一个人啊。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by superman-death** [comment]
你谁？在骚扰我可就骂人了

**Comment by fenice8023** [comment]
我就是之前的fenice那个账号，一名学生，之前您说我公开了您的课件，然后我就给您道个歉





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuangCongQing/UCAS_Course_2019"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月25日(星期三) 中午1:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuangCongQing/UCAS_Course_2019] 同学，你获得老师的许可了么？就直接公开老师的课件。 (#1)





 你谁？在骚扰我可就骂人了
 
 &gt; 在 2021年8月25日，下午1:11，Lidong ***@***.***&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; 嗯嗯，以后常联系
 &gt; …
 &gt; ------------------ 原始邮件 ------------------ 发件人: "HuangCongQing/UCAS_Course_2019" @.&gt;; 发送时间: 2021年8月25日(星期三) 中午1:09 @.&gt;; @.@.&gt;; 主题: Re: [HuangCongQing/UCAS_Course_2019] 同学，你获得老师的许可了么？就直接公开老师的课件。 (#1) 没有全部公开，有部分课程，老师不让发布到网上，就没有发布！(^▽^) 了解 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
 &gt; 
 &gt; 哦哦，俩账号是一个人啊。
 &gt; 
 &gt; —
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
